name: Deploy to EC2

on:
  push:
    branches:
      - main  # or whichever branch you deploy from

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy via SSH
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/odrindia

            # Reset local changes just in case
            git reset --hard

            # Pull the latest code
            git pull origin main

            # Install dependencies
            npm install

            # Build the Next.js app
            npm run build

            # Restart PM2 process (or start if not running)
            pm2 describe odrindia > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart odrindia
            else
              pm2 start npm --name odrindia -- start
              pm2 save
            fi
          EOF
